<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ofDaSm\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ofDaSm/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container4ofDaSm.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container4ofDaSm\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container4ofDaSm\App_KernelTestDebugContainer([
    'container.build_hash' => '4ofDaSm',
    'container.build_id' => '08c2a11d',
    'container.build_time' => 1671271448,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4ofDaSm');
