<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'cart_index' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/panier']], [], [], []],
    'cart_add' => [[], ['_controller' => 'App\\Controller\\CartController::addToCart'], [], [['text', '/panier/add']], [], [], []],
    'cart_clear' => [[], ['_controller' => 'App\\Controller\\CartController::clearCart'], [], [['text', '/panier/clear']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::homepage'], [], [['text', '/']], [], [], []],
    'product_list' => [[], ['_controller' => 'App\\Controller\\ProductController::list'], [], [['text', '/produits']], [], [], []],
    'product_show' => [['id'], ['id' => '13', '_controller' => 'App\\Controller\\ProductController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/produits/see']], [], [], []],
];
