<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLcNiPQ3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLcNiPQ3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLcNiPQ3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLcNiPQ3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLcNiPQ3\App_KernelDevDebugContainer([
    'container.build_hash' => 'LcNiPQ3',
    'container.build_id' => '68717fd5',
    'container.build_time' => 1671380787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLcNiPQ3');
