<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5VYCzG0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5VYCzG0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5VYCzG0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5VYCzG0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5VYCzG0\App_KernelDevDebugContainer([
    'container.build_hash' => '5VYCzG0',
    'container.build_id' => 'bb11bb3a',
    'container.build_time' => 1671367814,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5VYCzG0');
