<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxBbxfB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxBbxfB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxBbxfB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxBbxfB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUxBbxfB\App_KernelDevDebugContainer([
    'container.build_hash' => 'UxBbxfB',
    'container.build_id' => 'b9c0f79d',
    'container.build_time' => 1671436721,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxBbxfB');
